version: "3"
name: python

services:
  builder:
    build:
      args:
        PYTHON_SERIES: ${PYTHON_SERIES}
        TARGET_OS: ${TARGET_OS}
      context: ${PWD}
      dockerfile: targets/${TARGET_OS}/Dockerfile
      tags:
        - infra7/python:${PYTHON_SERIES}-${TARGET_OS}
        - infra7/python:${PYTHON_VERSION}-${TARGET_OS}
    image: infra7/python:${PYTHON_VERSION}-${TARGET_OS}
    network_mode: host
