version: "3"
name: python

services:
  builder:
    build:
      args:
        PYTHON_SERIES: ${PYTHON_SERIES}
        TARGET_OS: ${TARGET_OS}
      context: ${PWD}
      dockerfile: targets/${TARGET_OS}/Dockerfile
    image: python:${PYTHON_VERSION}-${TARGET_OS}
    network_mode: host
