name: Makefile CI

on:
  push:
    branches: [ "workflows" ]
  pull_request:
    branches: [ "workflows" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Images
      run: make repo=infra7 target/bookworm
